title: Fabricio Layedra # your name (or website title) here
description: < # your text below (remove <br> elements if you don't need line breaks)
  Google Summer of Code Final Report
  viNLaP
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
 	
theme: jekyll-theme-minimal
